### ISSUE TITLE
Feature Request: Set background image from URL on canvas.

### ISSUE THREAD

**Issue by ankit18singh** [terrylinla/react-native-sketch-canvas#112]
Hi,
The plugin works great with the locally stored images but I cannot see any option to use images using URL. Since in my use-case, the background images will change dynamically.

Please let me know how can I achieve this with this plugin or guide me to a plugin which can help me with this task.

Thanks.

**Comment by jedabero** [comment]
Hi @ankit18singh I think you can set an external image as background by downloading it to the device

Check https://github.com/terrylinla/react-native-sketch-canvas#localsourceimage-object
