### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.UIManager.RNSketchCanvas.Constants')

### ISSUE THREAD

**Issue by leonyhenn** [terrylinla/react-native-sketch-canvas#116]
This happens on ios only, did a ton of search, seems there is something wrong in the code. Please help.

![image](https://user-images.githubusercontent.com/16746119/57244441-5d5cfa80-7006-11e9-8c21-190e16063470.png)

**Comment by leonyhenn** [comment]
Or is it a linking problem? by the way after I manually link the library to xcode under instruction [https://github.com/terrylinla/react-native-sketch-canvas/issues/45](url) , xcode shows build failed

**Comment by leonyhenn** [comment]
Linking problem, which is solved. issue closed.

**Comment by chrisronline** [comment]
@leonyhenn What was the linking problem?

**Comment by Nirodha26** [comment]
@leonyhenn I'm facing the same issue. How did you resolve it?

**Comment by Rache-lBronfman** [comment]
Has anyone found any solution to this?
