### ISSUE TITLE
Does not save sketch in Android 10

### ISSUE THREAD

**Issue by akshit5230** [terrylinla/react-native-sketch-canvas#142]
onSketchSaved callback returns success false and path null

"@terrylinla/react-native-sketch-canvas": "^0.8.0",
"react": "16.8.6",
"react-native": "0.60.5",
buildToolsVersion = "29.0.2"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
supportLibVersion = "28.0.0"

**Comment by vietmobilefolk** [comment]
You should check if write permission is granted or not.

**Comment by akshit5230** [comment]
I found the issue. It was because Android 10 does not (by default) allow creating folders in storage. So there's a flag which we can set in the application element in android manifest to enable this.
`android:requestLegacyExternalStorage="true"`

See more here: https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10

**Comment by sysunny** [comment]
> I found the issue. It was because Android 10 does not (by default) allow creating folders in storage. So there's a flag which we can set in the application element in android manifest to enable this.
> `android:requestLegacyExternalStorage="true"`
> 
> See more here: https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10

thanks

**Comment by steventilator** [comment]
I've had success by requesting the permissions READ_EXTERNAL_STORAGE and
WRITE_EXTERNAL_STORAGE explicitly before saving: https://reactnative.dev/docs/permissionsandroid

**Comment by shubhamnishad** [comment]
Thanks it helped me
