### ISSUE TITLE
Rotated View Not Drawing With Rotated Direction

### ISSUE THREAD

**Issue by tnorlund** [terrylinla/react-native-sketch-canvas#161]
<img width="461" alt="Screen Shot 2020-05-28 at 11 58 00 AM" src="https://user-images.githubusercontent.com/26452518/83181975-7be2d780-a0da-11ea-923d-c03ae7e2eaa0.png">
Hey guys. I'm trying to place this component in a rotated view. When I then draw on the RNSketchCanvas, the strokes are not transformed like the view. Is there a way to transform the strokes after transforming the view?

**Comment by react06** [comment]
hey @tnorlund, did you resolve this issue? because I'm facing the same. Could you please help?
