### ISSUE TITLE
canvas is not getting saved in SketchCanvas component

### ISSUE THREAD

**Issue by devendra-learngram-ai** [terrylinla/react-native-sketch-canvas#172]
I'm using SketchCanvas component for custom ui. my SketchCanvas looks like this:
`<SketchCanvas
            ref={(ref) => (this.canvas = ref)}
            style={{ flex: 1 }}
/>`

I'm trying to save the canvas by doing ```
this.canvas.save("png", true, "folderName", "filename", false, false, false ); ```. But when I check for the image, It is not there.
What could be the issue here ?

**Comment by anjusr** [comment]
Did you get any solution?

**Comment by YASH6004** [comment]
@devendra-learngram-ai what's the solution
