### ISSUE TITLE
on iOS SketchCanvas save and getBase64 functionalities are not working

### ISSUE THREAD

**Issue by vinothpandian** [terrylinla/react-native-sketch-canvas#19]
Thank you for this awesome library. It works perfectly on Android.

On iOS simulator, it crashes when I try to save the SketchCanvas using save() method and returns an empty canvas base64 with getBase64 callback function. Both these features work on android though. I am not getting any other error message in the debugger.

I am using react-native 0.52.0

**Comment by terrylinla** [comment]
Remember to add `NSPhotoLibraryAddUsageDescription` in Info.plist.
And remind that getBase64 callback accepts 2 arguments.
BTW, we have published new version related to getBase64.
