### ISSUE TITLE
How do we load previously generated paths?

### ISSUE THREAD

**Issue by flyingbuddha** [terrylinla/react-native-sketch-canvas#2]
Firstly, thanks for writing this component.

I'd like to control the UI side of things myself and just make use of `SketchCanvas` but I'm struggling to understand how I can apply previous paths.

If I store an array of paths (`sketch`) as [described in the docs](https://github.com/terrylinla/react-native-sketch-canvas#path-format) and have the following in my app:

```
componentDidMount() {
  sketch.map((movement) => {
    console.log('drawing', movement.path)
    this.refs.canvas.addPath(movement)
  })
}
```

I would expect the canvas to display them but it remains blank. It could be that I have to somehow invalidate the render so it redraws, but I'm unsure if what I'm trying to accomplish is supported.

**Comment by terrylinla** [comment]
I have fixed this bug! Thanks!

**Comment by haideralishah** [comment]
> I have fixed this bug! Thanks!

how sir
