### ISSUE TITLE
Is the project dead? Anyone who forked, improved and continue this project?

### ISSUE THREAD

**Issue by persunde** [terrylinla/react-native-sketch-canvas#205]
It seems that this project is abandoned.
Have anyone else forked the project and continued to develop/maintain this project?

Any other alternatives I should consider for a React Native drawing app?

**Comment by mlecoq** [comment]
We have just released https://github.com/ArchireportTeam/react-native-svg-draw 

It's still a work in progress, but if you want to contribute you are welcomed

**Comment by persunde** [comment]
@mlecoq thank you for the response.
I do not have the resources to help develop a drawing library at the moment, but I will keep that in mind.
