### ISSUE TITLE
Android: Native component for "RNSketchCanvas" does not exist

### ISSUE THREAD

**Issue by marcelkussin** [terrylinla/react-native-sketch-canvas#22]
in iOS its working but sadly not on android with "react-native run-android"

code:
...
import { SketchCanvas } from '@terrylinla/react-native-sketch-canvas';
...
render() {
...
<SketchCanvas 
                                   ref={ref => this.canvas = ref} 
                                   style={{ flex: 1 }}
                                   strokeColor={'red'}
                                   strokeWidth={7}
                              />
...
}

**Comment by terrylinla** [comment]
Please make sure all the steps in https://github.com/terrylinla/react-native-sketch-canvas/wiki/Manual-Linking-Android are done!
Sometimes react-native link misses some instructions.

**Comment by marcelkussin** [comment]
i used the wrong (old) android sdk

**Comment by RamiroIsBack** [comment]
Hello there, I'm experiencing the exact same problem but for IOS, do you have instructions to link it manually with Xcode ?
