### ISSUE TITLE
Android sketch 'pen' is square in shape; end caps are not round, and mid-stroke sometimes reveals a square pixel

### ISSUE THREAD

**Issue by toblerpwn** [terrylinla/react-native-sketch-canvas#23]

**Comment by terrylinla** [comment]
Square caps become round in new version! And I apply quadTo to draw the curve lines. Please check whether square pixel is disappeared or not! Thanks!

**Comment by toblerpwn** [comment]
Oh, awesome! I’ll check out version 0.3.1 and confirm.

(This ticket was made for 0.2.0)

**Comment by toblerpwn** [comment]
This works great now in `0.3.1`. Still having some smoothing/jaggy issues (different issue), but the end caps are working properly. Thanks @terrylinla!
