### ISSUE TITLE
Curved lines are not 'smooth'; use literal pixel interpretation

### ISSUE THREAD

**Issue by toblerpwn** [terrylinla/react-native-sketch-canvas#25]
Typical implementations on iPhone use a quadratic curve implementation, which requires that the two previous points to be available (which I think we have stored in an array, fortunately!).

While a smooth line may not be desirable in all use cases, we should still have support for it (e.g. via Prop) - this is preferred certainly for any sort of 'signature'-type component, but also probably for the majority of free drawing applications.

@terrylinla - I have some experience with this on iPhone, and will submit a PR within the next few weeks if you don't beat me to it. Haven't looked into Android before.

**Comment by terrylinla** [comment]
I use quadTo instead of lineTo in Android. But it seems not to be obvious... Maybe something wrong!

**Comment by toblerpwn** [comment]
Oh, awesome! I’ll check out version 0.3.1 and confirm.

(This ticket was made for 0.2.0)

**Comment by hugpointgames** [comment]
@terrylinla PR submitted! See above. I implemented the iPhone version and improved your Android code.
