### ISSUE TITLE
[ios] Should/Could canvas manager create new canvas every time it gets called?

### ISSUE THREAD

**Issue by marsonmao** [terrylinla/react-native-sketch-canvas#35]
I mean this part of `RNSketchCanvasManager`:

```
    if (!self.sketchCanvasView) {
        self.sketchCanvasView = [[RNSketchCanvas alloc] initWithEventDispatcher: self.bridge.eventDispatcher];
    }
```
I'd like to remove the `if` check, but not sure if it's good. I'll explain my use case below.

I'm utilizing the `SkecthCanvas` component to implement something like a sketchbook. And I may have several sketchbooks available at the same time, but only 1 of them is active on the screen. I'd like all of them to be independent and have their own strokes, of course. However, if I close number 1 and open number 2, the strokes of number 1 is still showing on number 2, obviously it's because there is only 1 true canvas. That's why I'm thinking of creating new canvas every time it's called.

So if anyone or the author would give some advice it would be appreciated, thanks.

**Comment by terrylinla** [comment]
#43 fixed this issue
