### ISSUE TITLE
Render passes are very inefficient; re-renders entire canvas every frame!

### ISSUE THREAD

**Issue by toblerpwn** [terrylinla/react-native-sketch-canvas#39]
The goal here should be to only re-render the small part of the canvas that has changed (been drawn on) between each frame.

Here are two helpful blog posts about smoothing (and other things) on Android:

https://medium.com/square-corner-blog/smooth-signatures-9d92df119ff8 (see the "Surgically Invalidate" section)

https://medium.com/square-corner-blog/smoother-signatures-be64515adb33 (see the "Responsiveness" section)

Note that the same principles apply to iOS - but the methods will differ, slightly. For example, in one project I used the `UIView` object's `setNeedsDisplayInRect:` and specified only the rect/space representing the space between the last two touches to be re-rendered.

**Comment by jeanregisser** [comment]
I've started working on this.
Here's a first iOS implementation: https://github.com/crossfield/react-native-sketch-canvas/commit/7ef9bb4e77bc169b7bef6aeff239879bc6f58dfb

It dramatically improves the performance.

**Comment by jeanregisser** [comment]
I've implemented it first Android as well: https://github.com/crossfield/react-native-sketch-canvas/commit/1b14386bb9088f1466463742c10b65cc4d425e66

Now I need to restore the line smoothing which I lost by doing the incremental drawing.

**Comment by jeanregisser** [comment]
Line smoothing is back:
- iOS: https://github.com/crossfield/react-native-sketch-canvas/commit/d774c8a314ea749c2bf08c63e0ca3fab14acae59
- Android: https://github.com/crossfield/react-native-sketch-canvas/commit/b6aff9f2e878fdbb32356358d8687ff7ad0252ae

**Comment by toblerpwn** [comment]
@jeanregisser This is VERY amazing! Would you mind making a PR into this repo? @terrylinla has been good about reviewing & merging what gets submitted (although sometimes it takes a few weeks).

Also I'll test this in our app soon. :)

**Comment by terrylinla** [comment]
I have merged into repo and published to npm! It's really awesome!!

**Comment by terrylinla** [comment]
It looks awesome! Making a PR is welcome!

**Comment by jeanregisser** [comment]
I'll send a PR as soon as I can!

**Comment by terrylinla** [comment]
Thanks a lot!! I appreciate your contribution!

**Comment by toblerpwn** [comment]
fixed in #53
