### ISSUE TITLE
Error linking on iOS app

### ISSUE THREAD

**Issue by criestlav** [terrylinla/react-native-sketch-canvas#44]
Hi,

I am trying to implements this library in an iOS app. I have already used it on an Android app but when i use: react-native link @terrylinla/react-native-sketch-canvas

It returns to me the next error:

rnpm-install info Android module @terrylinla/react-native-sketch-canvas is already linked
rnpm-install info Linking @terrylinla/react-native-sketch-canvas ios dependency
rnpm-install WARN ERRGROUP Group 'Libraries' does not exist in your Xcode project. We have created it automatically for you.
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'children' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Can anyone help me?

Thanks!!

**Comment by terrylinla** [comment]
Hi~

I ran "react-native link" to link my project to a new react-native project just now and it works.
You can try "react-native link @terrylinla/react-native-sketch-canvas" to link my project only.
