### ISSUE TITLE
Linking on iOS

### ISSUE THREAD

**Issue by criestlav** [terrylinla/react-native-sketch-canvas#45]
Hi!

How can I link this library manually on iOS? It works for me in Android but not in iOS.

Thank you!

**Comment by terrylinla** [comment]
Follow the instructions in react-native official documents.
Here is the link~ You can skip step 3. It's not necessary.
[https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

**Comment by criestlav** [comment]
Thanks! I had problem with my dependencies and versions. Finally, this probles was fixed. Thanks!
