### ISSUE TITLE
Unable to find module with Gradle path ':@terrylinla/react-native-sketch-canvas' (needed by module 'app'.)

### ISSUE THREAD

**Issue by aaeronn** [terrylinla/react-native-sketch-canvas#52]
I do not know why this issue is coming when I open android studio.

But when I run the app it works fine. Why am I seeing this error ??

**Comment by ShaunLWM** [comment]
Android Studio is unable to resolve file path with `/` for in the include statement.
Replace the module with this line in your project `settings.gradle`

```
include ':@terrylinla_react-native-sketch-canvas'
project(':@terrylinla_react-native-sketch-canvas').projectDir = new File(rootProject.projectDir, '../node_modules/@terrylinla/react-native-sketch-canvas/android')
```

**Comment by aaeronn** [comment]
I have same code in my project setting.gradle.  I dont know why I am getting this error

**Comment by ShaunLWM** [comment]
Have you changed the `/` to `_`?

Use `:@terrylinla_react-native-sketch-canvas` and not `:@terrylinla/react-native-sketch-canvas`

**Comment by terrylinla** [comment]
In `settings.gradle`, you may also need to change
```
compile project(':@terrylinla/react-native-sketch-canvas')
```
to
```
compile project(':@terrylinla_react-native-sketch-canvas')
```

**Comment by aaeronn** [comment]
Yes changing "/" to "_" in settings.gradle and build.gradle worked for me.. I guess it is issue with android studio 3

**Comment by terrylinla** [comment]
Close this issue. Feel free to re-open if you still have same problem!

**Comment by vietmobilefolk** [comment]
Still got the problem after change "/" to "_" in _settings.gradle_ and _app/build.gradle_
