### ISSUE TITLE
   localSourceImagePath="../assets/images/splash/splash2.png"   is not working

### ISSUE THREAD

**Issue by gmchaturvedi1** [terrylinla/react-native-sketch-canvas#58]
i am new to this library fantastic work but when i want to load image as background is not working.

Kindly suggest if i am doing wrongly 

   localSourceImagePath="../assets/images/splash/splash2.png"

thanks & Regards
gmchaturvedi

**Comment by princepardeep** [comment]
Same here

**Comment by diego-caceres-galvan** [comment]
Hi. I don't think local assets to the project are supported in this case yet. The idea for now was to be able to draw on a picture taken by the camera, so the path it is expecting is more like "file:///..." to a picture in the cellphone memory. 

I suppose that this would be a nice adding for the library.

**Comment by terrylinla** [comment]
I've done this part in my computer. It can pass a local asset/resource filename to localSourceImagePath.
But I'm also merging PR meanwhile and face some problems...
So it may take some time to release a new version.

**Comment by princepardeep** [comment]
Done by using react-native-image-picker it provides both i.e gallery as well as the camera for capturing the images. thanks @diego-caceres-galvan

**Comment by terrylinla** [comment]
I have released a new version. You can try it.
Feel free to reopen this issue if there is still a problem.
