### ISSUE TITLE
SketchCanvas gets cut off in landscape mode in iOS

### ISSUE THREAD

**Issue by isghanim** [terrylinla/react-native-sketch-canvas#59]
In iOS, when I change the device orientation to landscape, my drawings are only visible on one half of the canvas.

<img width="331" alt="screen shot 2018-07-20 at 3 32 16 pm" src="https://user-images.githubusercontent.com/17101391/43021575-20dc411e-8c32-11e8-94c8-49f650725d1c.png">

I know the canvas is taking up the whole area, because I made the background colour of the SketchCanvas red.

It seems like the canvas size isn't being updated on rotation. The weird part is that if I redraw the paths from the landscape canvas onto another canvas, it shows the full drawing.

**Comment by terrylinla** [comment]
Release 0.7.0 fixes this issue. You can try it!

**Comment by isghanim** [comment]
That's awesome!!! I just tried it out and it works!

Thanks for making another release by the way, this library is super cool! I work at a company called Dot Health, and I implemented a signature solution using your library! So thanks a lot!!

**Comment by terrylinla** [comment]
It is @jeanregisser's contribution! Say thanks to him!
