### ISSUE TITLE
onSketchSaved can not return filepath in android and also in success it return false

### ISSUE THREAD

**Issue by ankits47b** [terrylinla/react-native-sketch-canvas#62]
onSketchSaved can not return filepath in android and also in success it return false

    onSketchSaved={(success, filePath) => {
        console.log('onSketchSaved', 'filePath: ' + filePath);
     }}

**Comment by terrylinla** [comment]
What is your android version?

**Comment by ankits47b** [comment]
Fix this by giving permission (Hard permission using permission dialog)to write file
