### ISSUE TITLE
Prevent Event Bubbling

### ISSUE THREAD

**Issue by dawidvdh** [terrylinla/react-native-sketch-canvas#64]
Is there any way to prevent event bubbling? I am currently using this with in a ScrollView thats within a TabView so if I try and draw either vertically or horizontally it seems as if though the ScrollView/Tab takes over. Any way of preventing event bubbling so that when I am drawing within the canvas the ScrollView/Tab wont gent any events?

This is probably related to #57

**Comment by terrylinla** [comment]
If you want to prevent scrolling the scrollview or swiping tab while drawing, you can set `scrollEnabled ` to `false` and `swipeEnabled ` to `false` in `onStrokeStart `.

[Here](https://github.com/terrylinla/react-native-sketch-canvas/blob/master/example/App.js#L560) is the example for scrollview.

These may be useful if you're using React Navigation
https://reactnavigation.org/docs/en/material-top-tab-navigator.html#swipeenabled
https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title

**Comment by dawidvdh** [comment]
@terrylinla yes I am aware, was just wondering if there isn't a way to just have an option for this to control the scrolling etc instead of having to do it independently in react-navigation and such. However this is resolved now thanks
