### ISSUE TITLE
Error attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by dhanangpratama** [terrylinla/react-native-sketch-canvas#67]
I got this error when using custom UI. below the code for save image:

`<SketchCanvas
                        ref={ref => this.canvas = ref}
                        style={{ flex: 1 }}
                        strokeColor={this.state.strokeColor}
                        strokeWidth={this.state.strokeSize}`

and the save method:

`<TouchableOpacity onPress={() => { this.canvas.save('jpg', true, '', 'test', true, true) }} style={styles.btn}>
                            <Icon name="check" size={26} color="black" />
                        </TouchableOpacity>`

Any wrong with my code?
Thank you! ^__^

**Comment by ggunti** [comment]
Same error at me

**Comment by ggunti** [comment]
I found the problem.
The documentation say that save function look like this: `save(imageType, transparent, folder, filename, includeImage, cropToImageSize)`, but it actually is `save(imageType, transparent, folder, filename, includeImage, includeText, cropToImageSize)`. Is missing the **includeText** parameter from documentation.

So in your case you could change `this.canvas.save('jpg', true, '', 'test', true, true)` to `this.canvas.save('jpg', true, '', 'test', true, false, true)` and it should work.

**Comment by dhanangpratama** [comment]
Thank you @ggunti, you save my life! ^__^
