### ISSUE TITLE
Behave strange when scaled and moved

### ISSUE THREAD

**Issue by waningflow** [terrylinla/react-native-sketch-canvas#68]
When the canvas is scaled and moved, the point you touch will be different with the point it really paints. It behaves like the gesture is also transformed. How can I avoid this?

**Comment by waningflow** [comment]
I update some source code of "SketchCanvas.js" and I've solved this.

**Comment by DanielBoening** [comment]
I'm currently facing the same issue. Can you tell me what you changed?

**Comment by waningflow** [comment]
Pass the scale number to the <SketchCanvas> component. And change the "onPanResponderMove" method in the "SketchCanvas.js".
```
onPanResponderMove: (evt, gestureState) => {
        if (!this.props.touchEnabled) return
        if (this._path) {
          const x = parseFloat((gestureState.x0 + gestureState.dx / this.props.scale - this._offset.x).toFixed(2)),
                y = parseFloat((gestureState.y0 + gestureState.dy / this.props.scale - this._offset.y).toFixed(2))
          UIManager.dispatchViewManagerCommand(this._handle, UIManager.RNSketchCanvas.Commands.addPoint, [
            parseFloat(x * this._screenScale),
            parseFloat(y * this._screenScale)
          ])
          this._path.data.push(`${x},${y}`)
          this.props.onStrokeChanged(x, y)
        }
      }
```

**Comment by DanielBoening** [comment]
Actually I did misunderstand your problem. Drawing on the correct position works for me out of the box if I zoom. However, the paths are not updated when I zoom. I adapt the whole canvas by applying a style with the updated width and height, which works great. But the paths are not updated, so as soon as I zoom, the paths are no longer at the correct position. 
Would be great if you could help me!

**Comment by waningflow** [comment]
You'd better use transform scale style but not changing the width and height of the canvas.

**Comment by DanielBoening** [comment]
Thank you, it works great. You saved my day!

**Comment by carpaldeveloper** [comment]
@DanielBoening how did you solve it ? i am stuck at this

**Comment by shaikhalid** [comment]
> 
> 
> @DanielBoening how did you solve it ? i am stuck at this

Hey guys how are zooming the canvas??

**Comment by shaikhalid** [comment]
> 
> 
> Pass the scale number to the component. And change the "onPanResponderMove" method in the "SketchCanvas.js".
> 
> ```
> onPanResponderMove: (evt, gestureState) => {
>         if (!this.props.touchEnabled) return
>         if (this._path) {
>           const x = parseFloat((gestureState.x0 + gestureState.dx / this.props.scale - this._offset.x).toFixed(2)),
>                 y = parseFloat((gestureState.y0 + gestureState.dy / this.props.scale - this._offset.y).toFixed(2))
>           UIManager.dispatchViewManagerCommand(this._handle, UIManager.RNSketchCanvas.Commands.addPoint, [
>             parseFloat(x * this._screenScale),
>             parseFloat(y * this._screenScale)
>           ])
>           this._path.data.push(`${x},${y}`)
>           this.props.onStrokeChanged(x, y)
>         }
>       }
> ```

I did this exact change the gesture starts right but the difference keeps on increasing as I draw
