### ISSUE TITLE
Cant get localSourceImage to load image from camera or gallery

### ISSUE THREAD

**Issue by MichaelTaylor3d** [terrylinla/react-native-sketch-canvas#78]
I just ejected from Expo in order to activate this module and I can get the vanilla sketchpad example to show up in the app. Im still using ExpoKit, Using the ExpoKit image picker, and Im using the IOS emulator. I can get an image URI from the gallery or I can snap a photo from the non existant camera (produces a black image).

If I get an image from the gallery the URI is in the format "file://really/long/path/to/file.jpg"
If I get an image from tha camera the URI is in the format "asset-library://asset.jpg&id=someId"

I cant get either one of these URIs to load into the sketch canvas.
The sketch canvas is still functional it just does not load the image.

I have not had a chance to get this on a physical device yet, my results are through the ios emulator. 
To me possible issues may be:

- works on device but not emulator (havnt gotten it on a physical device yet)
- maby the expoKit URIs are different then Native URIs so it cant find the image
- my code is wrong

Any thoughts here?

Thanks,
Michael

```
const srcImage = {
  filename: uriRetreivedFromCamera.jpg,
  directory: '', 
  mode: 'AspectFill'
}

```
Then somewhere in the JSX

```
<SketchCanvas
     style={{ flex: 1 }}
     strokeColor={'red'}
     strokeWidth={7}
     localSourceImage={srcImage}
 />
```

**Comment by bvodola** [comment]
@MichaelTaylor3D I was facing the same issue and maybe this will help:

Remove the `file://` from your image URI retrieved from the camera:

`uri.replace('file://', '')`

If you take a look at the example code from this repo,
https://github.com/terrylinla/react-native-sketch-canvas/blob/master/example/App.js#L37
he does exactly that.

**Comment by MichaelTaylor3d** [comment]
that seems to work, thanks

**Comment by leonyhenn** [comment]
@MichaelTaylor3D I am facing the exact issue that you had. Detach from expo, result from imagePicker looks like this:

file:/data/user/0/mosaic/cache/ExperienceData/%2540leonyhenn%252FMosaic/ImagePicker/2a4a9f89-142f-4f5c-9163-f36eb9cb9f58.png

which this module won't parse. Can you please share how exactly did you solve the problem? I tried @bvodola 's solution , remove the head 'file:/' and replace with '', but it still gives nothing.

**Comment by leonyhenn** [comment]
Ok, I figured out a solution. I ll post it here in case someone like me stuck at this step.

Remember, you have already ejected!!! which means now you have access to all the powerful library in expo community such as react-native-fs.

My solution is, get the base64 of image, then use react-native-fs to store it in a temp folder anywhere in the filesystem, then reference it use react-native-fs which gives you a path that native component can recognize.

**Comment by marcelo-tm** [comment]
> Ok, I figured out a solution. I ll post it here in case someone like me stuck at this step.
> 
> Remember, you have already ejected!!! which means now you have access to all the powerful library in expo community such as react-native-fs.
> 
> My solution is, get the base64 of image, then use react-native-fs to store it in a temp folder anywhere in the filesystem, then reference it use react-native-fs which gives you a path that native component can recognize.

Please can you share how you solved this issue? I'm facing the same problem with camera image and gallery image.

**Comment by leonyhenn** [comment]
i think i have wrote all the steps @maverickVision

**Comment by marcelo-tm** [comment]
It's because I followed the steps but the image still isn't loading, but if I try using an Image component, the image loads. Here's my code:

```
handleGalleryTap = async () => {
    const image: any = await ImagePicker.openPicker({})
    const base64Image = await RNFS.readFile(image.path, 'base64')
    const path = `${RNFS.DocumentDirectoryPath}/${this.props.user.id}${moment().valueOf()}.jpg`
    RNFS.writeFile(path, base64Image, 'base64')
        .then(() => console.log('success')).catch(e => console.log(e))
    this.props.navigation.navigate('StoryCustomizeScreen', {uri: path})
}
```
Then in the next screen I have the canvas:

```
<SketchCanvas
    style={{ flex: 1 }}
    strokeColor={'red'}
    strokeWidth={7}
    localSourceImage={{ path, directory: null, mode: 'AspectFill' }}
 />
```
This is an example of the path string:

`/Users/marcelo/Library/Developer/CoreSimulator/Devices/273158EF-6BC4-4780-A832-00BDD1E1A059/data/Containers/Data/Application/6719F010-E3C5-425E-A815-2E41732195C5/Documents/kAV3BM2kFW1558704640000.jpg`

I'm using the iPhone simulator, but I think this would not be the issue, since I can draw on the canvas.

**Comment by marcelo-tm** [comment]
I found the issue, it's something with typings... Typescript was showing me errors when i added the "filename" property to localSourceImage, and suggested to use the "path" param instead. Now I tried using the filename even with the error on screen and the image loaded...

<img width="1067" alt="error" src="https://user-images.githubusercontent.com/26512527/58332673-1ba7be80-7e12-11e9-8c99-1c4c78c0e393.png">

**Comment by leonyhenn** [comment]
I just wake up. As I remember there are some issues with filesystem in
simulator. Any chance u can run it on a real device?

**Comment by marcelo-tm** [comment]
I got it working after a lot of research here, but that typing problem is still here. I have a tight schedule today, so I'm leaving it for another time, as it is working fine.

**Comment by leonyhenn** [comment]
Kk, i ll post my code later when i get to the desk

**Comment by leonyhenn** [comment]
@maverickVision 
``` javascript
async _pickImage() {
    let result = await ImagePicker.launchImageLibraryAsync({base64:true});
    if (!result.cancelled) {
      base64 = result.base64
      extension =  result.uri.split('.').pop();
      
      decodedImage = decode(base64);
      // console.log(decodedImage)
      var path = DocDir + '/TempFile';
      new_filename = path+"/sample_image."+extension
      console.log(new_filename)
      //write the file
      RNFS.mkdir(path).then((success) => {
        RNFS.writeFile(new_filename, base64, 'base64').then((success) => {
            if(Platform.OS == 'ios'){
              this.setState({ photoPath: new_filename });
            }else{
              this.setState({ photoPath: new_filename });  
            }
          }).catch((err) => {
            console.log(err.message);
          });
      }).catch((err) => {
        console.log(err.message);
      });
    }
  };
```

that was what I had. and in the Sketch section:


``` javascript
<View style={{ flex: 1, flexDirection: 'row' }}>
              <RNSketchCanvas
                localSourceImage={{ filename: this.state.photoPath, directory: null, mode: 'AspectFit' }}
```

**Comment by fabricepayet** [comment]
> I found the issue, it's something with typings... Typescript was showing me errors when i added the "filename" property to localSourceImage, and suggested to use the "path" param instead. Now I tried using the filename even with the error on screen and the image loaded...
> 
> <img alt="error" width="1067" src="https://user-images.githubusercontent.com/26512527/58332673-1ba7be80-7e12-11e9-8c99-1c4c78c0e393.png">

The typing problem is still present in the package and prevent the display of the background image. I fix it by typing the localSourceImage as any. Ugly but working !

`
<SketchCanvas
          onSketchSaved={handleSaved}
          style={{ flex: 1 }}
          strokeColor={'red'}
          strokeWidth={7}
          localSourceImage={
            {
              filename: sourceImage,
              directory: '',
              mode: 'AspectFit'
            } as any
          }
          ref={canvas}
/>
`
